### PR TITLE
Enhanced Webpage by introducing Dark Theme

### PR DESCRIPTION
**Pull request by pooranjoyb**
### Description

With this enhancement, the webpage will now have a MUI Toggle Button that will toggle between Dark and Light Modes

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've made the enhancement both for light as well as dark modes
- [x] I ensured that the page remains responsive after the addition of the changes

## Related Issues or Pull Requests

#1  

## Add relevant screenshot or video (if any)

[video_demo.webm](https://user-images.githubusercontent.com/90945182/218547611-4d74092f-c06e-4382-8e6e-387a0df34621.webm)

### CODE REVIEW

**Comment by DevGautam2000** [comment]
@pooranjoyb 

Hi @pooranjoyb ,
There are a few bugs that I noticed

--- bugs

- the theme is not in state of the app
- upon refresh it loses the theme
- only partially done , the dark theme does not apply to the form , the loader, the result page either. It only works for the background

--- convention

- position of the switch to be on the right 
- switch color to match the color scheme

**Comment by pooranjoyb** [comment]
@DevGautam2000 Okay, I'm trying to fix it ! 
Would be glad if you please suggest me the workflow that'll do in the project.

**Comment by DevGautam2000** [comment]
> @DevGautam2000 Okay, I'm trying to fix it ! Would be glad if you please suggest me the workflow that'll do in the project.

what you need to do is

keep the theme in the state of the app
for that

- you need to initialise the theme variable whatever you have used in the project in a use effect hook that runs with no dependency 
- you may check the hook as in this screen [here](https://github.com/DevGautam2000/results-web/tree/main/src/screens/Home/Home.js)
     -- NOTE: use a different effect hook do not add it in the previous hooks(if any)
- then you need to make sure that the switch color matches the app colors.
- then making just the background black is not appreciated. The colors that are used also need to change to a darker shade of what it is in the light mode

--- like if you check the navbar has this config in the background = linear-gradient(90deg,#6302ff 50%,#3955f6);
--- when in dark mode it needs to change to this linear-gradient(90deg,#4b06ba 50%,#1e37cb);
--- also add the dark mode to the loader , form , the result page

Any query:  mail at devgautam1231@gmail.com

**Comment by pooranjoyb** [comment]
Appreciating your response. Working into it asap! 🚀 @DevGautam2000

**Pull request closed without merging**
